import * as React from 'react';
import ThemeRegistry from '@/components/ThemeRegistry/ThemeRegistry';
import NextAuthProvider from '@/components/NextAuthProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout(props: { children: React.ReactNode }) {
  const { children } = props;
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <ThemeRegistry>{children}</ThemeRegistry>
        </NextAuthProvider>
      </body>
    </html>
  );
}
