import * as React from 'react';
import ThemeRegistry from '@/providers/ThemeRegistry/ThemeRegistry';
import NextAuthProvider from '@/providers/NextAuthProvider';
import { SnackBarProvider } from '@/providers/alertProvider';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout(props: { children: React.ReactNode }) {
  const { children } = props;
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <ThemeRegistry>
            <SnackBarProvider>
              {children}
            </SnackBarProvider>
          </ThemeRegistry>
        </NextAuthProvider>
      </body>
    </html >
  );
}
